# Generated by Django 3.0.3 on 2020-02-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tx_discrepancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discrepancy',
            options={'verbose_name_plural': 'Discrepancies'},
        ),
    ]
