# Generated by Django 3.0.3 on 2020-02-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tx_discrepancy', '0002_auto_20200217_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmitter', models.CharField(max_length=20)),
                ('component', models.CharField(max_length=20)),
                ('part_number', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tx_discrepancy.Site')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
