# Generated by Django 3.0.3 on 2020-02-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tx_inventory', '0002_auto_20200222_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='part_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='transmitter',
            field=models.CharField(max_length=50),
        ),
    ]
